#!/usr/bin/env bash
# fallback -- recodifica el stream a otros formatos
#
# © 2017 fauno <fauno@partidopirata.com.ar>
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.
# 
# http://www.gnu.org/prep/maintain/html_node/License-Notices-for-Other-Files.html

set -e
set -E

PROGRAM="$(basename -- "$0")"
ICECAST_PORT=${ICECAST_PORT:-8000}
ICECAST_SERVER=${ICECAST_SERVER:-partidopirata.com.ar}
ICECAST_PASSWORD=${ICECAST_PASSWORD:-hackme}
ICECAST_USER=${ICECAST_USER:-source}
ICECAST_CHANNEL=${ICECAST_CHANNEL:-${PROGRAM}}
VERBOSE=false
FORMAT=${FORMAT:-mp4}

# Obtiene la resolución actual
function get_resolution() {
  xrandr | grep '*' | tr -s ' ' | cut -d' ' -f2
}

function get_public_url() {
  echo "https://${ICECAST_SERVER}/${ICECAST_CHANNEL}.${FORMAT}"
}

function get_original_stream() {
  echo "${STREAM:-https://${ICECAST_SERVER}/${ICECAST_CHANNEL}.webm}"
}

function get_format_options() {
  local _options
  case ${FORMAT} in
    ogg) _options="-content_type application/ogg -vn" ;;
    mp4) _options="-content_type application/mp4" ;;
  esac

  echo "${_options}"
}

function get_icecast_url() {
  echo "icecast://${ICECAST_USER}:${ICECAST_PASSWORD}@${ICECAST_SERVER}:${ICECAST_PORT}/${ICECAST_CHANNEL}.${FORMAT}"
}

function retransmitir() {
  ${VERBOSE} || local _quiet="-loglevel quiet"
  ${VERBOSE} || local _wquiet="-q"

  get_icecast_url

  get_original_stream | \
  wget -i - ${_wquiet} -O - | \
  ffmpeg -i pipe: \
         ${_quiet} \
         -f ${FORMAT} \
         $(get_format_options) \
         $(get_icecast_url)
}

# Chequear que no estemos sourceando
function is_main() {
  test 'xfallback' = "x${PROGRAM}"
}

function help() {
  echo "${PROGRAM} -- Retransmitir"
  echo
  echo 'Uso:'
  echo
  echo "  [ICECAST_PASSWORD=${ICECAST_PASSWORD}] ./${PROGRAM} [-i ${STREAM}] [-vh] [-s ${ICECAST_SERVER}] [-p ${ICECAST_PORT}] [-c ${ICECAST_CHANNEL}] [-u ${ICECAST_USER}] [-f ${FORMAT}]"
  echo
  echo "La contraseña siempre se pasa como variable de entorno."
  echo
  echo "Con 'q' terminás de transmitir"
}

function main() {
  while getopts hvu:c:s:p:f:i: option; do
    case ${option} in
      h) help ; exit ;;
      v) VERBOSE=true ;;
      u) ICECAST_USER="${OPTARG}" ;;
      p) ICECAST_PORT="${OPTARG}" ;;
      s) ICECAST_SERVER="${OPTARG}" ;;
      c) ICECAST_CHANNEL="${OPTARG}" ;;
      f) FORMAT="${OPTARG}" ;;
      i) STREAM="${OPTARG}" ;;
    esac
  done
  shift $((${OPTIND} -1 ))

  ${VERBOSE} && echo -n 'Tu transmisión saldrá por: '
  get_public_url

  while ! retransmitir ; do
    sleep 2
  done
}

# Ejecutar el programa si no estamos sourceando
is_main && main $@
